name: Run tests with Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile.dev --tag dgazdag/docker-react
    - name: Run tests
      run: docker run -e CI=true dgazdag/docker-react npm run test
